---
     - name: "download wordpress"
       get_url:
          url: https://wordpress.org/latest.zip
          dest: /tmp/wordpress.zip
     - name: "unarchive wordpress"
       unarchive:
          src: /tmp/wordpress.zip
          dest: /var/www
          remote_src: yes
     - name: "create new db"
       mysql_db:
           name: "{{dataBaseName}}"
           state: present
     - name: "create db user"
       mysql_user:
            name: "{{dataBasesUser}}"
            password: 
            priv: '*.*:ALL'
     - name: "put apache conf"
       template: 
           src: templates/blog.conf
           dest: /etc/httpd/conf.d/blog.conf
     - name: "start http service"
       service:
         name: httpd
         state: restarted     
     - name: "put wp_config"
       copy:
           src: templates/wp-config.php
           dest: "{{wordpress_path}}/wp-config.php"
     - name: Update WordPress config file
       lineinfile:
           dest="{{wordpress_path}}/wp-config.php"
           regexp="{{ item.regexp }}"
           line="{{ item.line }}"
       with_items:
           - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{dataBaseName}}');"}        
           - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{dataBasesUser}}');"}        
  

